name: Build and Push

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build from'
        required: true
        default: 'main'
        type: string
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - 'README.md'
      - '.gitignore'
      - '.dockerignore'


jobs:
  build-and-push:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Get Commit SHA
      id: short_sha
      uses: benjlevesque/short-sha@v3.0

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet Packages
      run: nuget restore MovieReview.Web.sln

    - name: Build Application
      run: msbuild MovieReview.Web.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=LocalPublishProfile /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:publishUrl=publish

    # TODO: These don't seem to run as expected
    # the setup msbuild action does not add vstest to path so call it directly 
    # - name: Run Tests
    #   run: '"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" MovieReview.Web\bin\MovieReview.Test.dll'

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Buildkit allows the windows platform but it's support is experimental and
    # moby/buildkit doesn;t actually provide images for that arch
    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v3
    #   with:
    #     platforms: windows/amd64

    # - name: Build and push
    #   uses: docker/build-push-action@v6
    #   with:
    #     context: .
    #     push: true
    #     tags: alexgqq/movie-review-app:latest

    - name: Build Image and Push
      shell: powershell
      run: |
        docker build . `
          -t ${{ secrets.DOCKERHUB_USERNAME }}/movie-review-app:${{ steps.short_sha.outputs.sha }} `
          -t ${{ secrets.DOCKERHUB_USERNAME }}/movie-review-app:latest
        docker push --all-tags ${{ secrets.DOCKERHUB_USERNAME }}/movie-review-app
